name: release

on:
  push:
    tags:
      - "v*"

env:
  # TODO matrix when forge & fabric
  MOD_LOADER: fabric

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1

      - name: generate changelog and create release
        run: bunx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: generate_changelog
    strategy:
      matrix:
        branch: ["1.20.1", "1.20.2", "main"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{matrix.branch}}

      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: build
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      # idk how to do it in gradle
      # '1.20.4' is the newest version the main branch is on, update accordingly
      - name: rename jars
        working-directory: build/libs
        run: for file in *; do if [ -f "$file" ]; then filename="${file%.*}"; extension="${file##*.}"; mv "$file" "${filename}+${{env.MOD_LOADER}}_${{matrix.branch === 'main' && '1.20.4' || matrix.branch}}.${extension}"; fi; done

      - name: hi from ${{matrix.branch}}
        working-directory: build/libs
        run: |
          ls

  check_build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: check build?
        working-directory: build/libs
        run: |
          ls
