name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: generate changelog and create release
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: build
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: temp
        working-directory: build
        run: ls
