name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: echo "changelog_output=$(npx changelogithub)\n" >> $GITHUB_OUTPUT
        id: generate_changelog
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - run: |
          echo "hello"
          echo ${{steps.generate_changelog.*}}
